name: Set Helm Template Image Tag Value
author: Matt Wise
description: |-
  Using `yq`, updates a Helm chart's "image tag" value.
inputs:
  values_files:
    description: >-
      The path to the `values.yaml` file that you want to modify.
    required: true
    default: chart/values.yaml

  tag_keys:
    description: >-
      The dot-notation path to the YAML key (or keys, if listed as a CSV) that
      should be updated.
    required: true
    default: .image.tag

  tag_value:
    description: The destination tag (the new tag) to create and publish
    required: true

  bump_level:
    description: >-
      `patch`, `minor`, `major`, or `null` to skip bumping the Chart version.
    required: true
    default: patch
    

runs:
  using: docker
  image: Dockerfile
